server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:aws_learning}
    username: ${DB_USER:aws}
    password: ${DB_PASSWORD:aws}
  jpa:
    hibernate:
      ddl-auto: update

